/*
 Copyright truelogic Pty Ltd
This code may not be used without permission and is copyright truelogic Pty Ltd unless otherwise stated below.


 clipboard.js v1.7.1
 https://zenorocha.github.io/clipboard.js

 Licensed MIT ? Zeno Rocha
  This plugin is by itself as we need it in the main site and campaign view.
    We don't want to double up on it when we minify.
 For license information please see view.js.LICENSE.txt */
cbCV={s:{$b:"",videoRender:!0},init:function(a){$.extend(cbCV.s,a);5===a.tv&&cbCV.v5Init(a);cbCV.style.normalizeHex();"object"===typeof cbCV.s.forwardfriend?cbCV.ff.init({hash:cbCV.s.hash,subject:cbCV.s.forwardfriend.subject,body:cbCV.s.forwardfriend.body,social:cbCV.s.forwardfriend.social,title:cbCV.s.forwardfriend.title}):"object"===typeof cbCV.s.poll&&(cbCV.s.bfc=cbCV.s.xc,cbCV.poll.init({heading:cbCV.s.poll.heading,message:cbCV.s.poll.message,button:cbCV.s.poll.button}));cbCV.s.videoRender&&cbVideo.init({$c:cbCV.s.$b})},
v5Init:function(a){"c"===a.t?cbB5.View.postRender("campaignView"):cbB5.View.postRender("recipientWebView")},posMiddle:function(a){var b=$(window).height()/3-a.height()/2;0>b&&(b=0);a.css({top:b+"px",visibility:"visible"})},style:{}};cbCV.style.normalizeHex=function(a){$.each("mc ac bc bg fc bfc xc".split(" "),function(b,n){(b=cbCV.s[n])&&"#"===b.charAt(0)&&(b=b.replace("#",""),cbCV.s[n]=b)})};
cbCV.style.add=function(a){var b=cbCV.style.map.common,n=$(b.selector),k=$("head");"string"===typeof a&&(0===n.length&&k.append(b.csstext),0===$(a.selector).length&&k.append(cbCV.style.getCSSText(a)))};cbCV.style.getCSSText=function(a){a=cbCV.style.map[a];return a.parse?a.parse():a.csstext};
cbCV.style.map={common:{selector:".CBUI-css-common",csstext:'<style class="CBUI-css-common" type="text/css">.CBUI-hide{display: none !important;}.CBUI-visuallyHidden{visibility: hidden !important;}.CBUI-clear{zoom: 1;}.CBUI-clear:before, .CBUI-clear:after {content: "\u00020";display: block;height: 0;overflow: hidden;}.CBUI-clear:after {clear: both;}a.CBUI-ap {cursor: pointer;}</style>'},overlay:{selector:".CBUI-css-overlay",csstext:'<style class="CBUI-css-overlay" type="text/css">.CBUI-overlay{background-color: #333;filter: alpha(opacity=90);-ms-filter: "alpha(opacity=90)";opacity: .9;height: 0;position: absolute;top: 0;left: 0;width: 100%;z-index: 10000;}.CBUI-overlay-iframe{border: none;position: absolute;top: 0;left: 0;width 100%;z-index: 9999;}</style>'},
dialog:{selector:"CBUI-css-dialog",parse:function(){var a=this.csstext;a=a.replace(/\[BC\]/g,cbCV.s.bc);a=a.replace(/\[BG\]/g,cbCV.s.bg);a=a.replace(/\[FC\]/g,cbCV.s.fc);a=a.replace(/\[MC\]/g,cbCV.s.mc);a=a.replace(/\[AC\]/g,cbCV.s.ac);return a=a.replace(/\[BFC\]/g,cbCV.s.bfc)},csstext:'<style class="CBUI-css-dialog" type="text/css">.CBUI-dialog{font-size:13px;font-family:sans-serif;line-height:normal;position:absolute;left:0;right:0;margin:0 auto;width:100%;max-width:300px;z-index:10010}.CBUI-dialog a,.CBUI-dialog a:link,.CBUI-dialog a:active,.CBUI-dialog a:visited{color:#333;font-family:sans-serif;font-style:normal;font-weight:400;text-decoration:underline}.CBUI-dialog a:hover{color:#333;font-family:sans-serif;font-style:normal;font-weight:400;text-decoration:none}.CBUI-dialog .CBUI-dialog-button{font-weight:700}.CBUI-dialog-innerContainer{background-color:#fff;border:1px solid #[BC]}.CBUI-dialog-title{background-color:#[BG];color:#[FC];font-size:24px;padding:24px 30px;word-wrap:break-word;}.CBUI-dialog-content{color:#[MC];line-height:17px;padding:30px;word-wrap:break-word;}.CBUI-dialog-footer{text-align:right;padding:25px}.CBUI-dialog a.CBUI-dialog-close,.CBUI-dialog a.CBUI-dialog-close:link,.CBUI-dialog a.CBUI-dialog-close:active,.CBUI-dialog a.CBUI-dialog-close:visited,.CBUI-dialog a.CBUI-dialog-close:hover{color:#[BFC];margin-top:12px;padding:8px 16px;font-size:14px;border:0;border-radius:0;background:#[AC];word-wrap:break-word;}</style>'},
forwardFriend:{selector:"CBUI-css-forwardFriend",csstext:'<style type="text/css" class="CBUI-css-forwardFriend">#CBUI-forwardfriend-button{font-weight: bold;}#CBUI-forwardfriend-url{font-size: 12px;}#CBUI-forwardfriend-socialTitle{font-size: 15px;font-weight: bold;}#CBUI-forwardfriend-socialContent{overflow: auto;zoom: 1;}.CBUI-forwardfriend-socialIcon{background: url(\'https://c.contentsvr.com/social/social-x-circle-32x32.png\') 0 0 #fff;display: inline;float: left;height: 32px;margin: 8px 8px 0 0;outline: none;width: 32px;text-indent: -99999px;}#CBUI-forwardfriend-twitter{background-position: -32px 0;}#CBUI-forwardfriend-linkedin{background-position: -64px 0;}#CBUI-forwardfriend-myspace{background-position: -96px 0;}#CBUI-forwardfriend-stumbleupon{background-position: -128px 0;}#CBUI-forwardfriend-digg{background-position: -160px 0;}#CBUI-forwardfriend-delicious{background-position: -192px 0;}#CBUI-forwardfriend-reddit{background-position: -224px 0;}#CBUI-forwardfriend-tumblr{background-position: -256px 0;}#CBUI-forwardfriend-google{background-position: -288px 0;}</style>'}};
cbCV.overlay={};cbCV.overlay._showing=!1;cbCV.overlay.isShowing=function(){return cbCV.overlay._showing};cbCV.overlay.show=function(){var a=$(".CBUI-overlay"),b=cbCV.s.$b.height(),n=$(window).height();0===a.length&&(cbCV.overlay.build(),a=$(".CBUI-overlay"));n>b?a.height(n):a.height(b);$("object").addClass("CBUI-visuallyHidden");cbCV.overlay._showing=!0;a.removeClass("CBUI-hide")};cbCV.overlay.build=function(){cbCV.style.add("overlay");cbCV.s.$b.append(cbCV.overlay.html)};
cbCV.overlay.hide=function(){$("object").removeClass("CBUI-visuallyHidden");cbCV.overlay._showing=!1;$(".CBUI-overlay").addClass("CBUI-hide")};cbCV.overlay.html='<div class="CBUI-overlay CBUI-hide"></div>';cbCV.dialog={config:{}};cbCV.dialog._defaultConfig={title:"Success",content:"You were successful.",button:"Close",width:"300px",showClose:!0,preview:!1,onOpen:void 0,onClose:void 0};
cbCV.dialog.show=function(a){var b=$(".CBUI-dialog");$.extend(cbCV.dialog.config,{},cbCV.dialog._defaultConfig,a);if(cbCV.dialog.config.preview)cbCV.dialog.showPreview();else{cbCV.overlay.show();0===b.length&&(cbCV.dialog.build(),b=$(".CBUI-dialog"),cbCV.dialog.wire(b));$(".CBUI-dialog-title").html(cbCV.dialog.config.title);$(".CBUI-dialog-content").html(cbCV.dialog.config.content);$(".CBUI-dialog-close").html(cbCV.dialog.config.button);b.css("max-width",cbCV.dialog.config.width);cbCV.dialog.config.showClose||
$(".CBUI-dialog-footer").addClass("CBUI-hide");b.removeClass("CBUI-hide");if("function"===typeof cbCV.dialog.config.onOpen)cbCV.dialog.config.onOpen(b);cbCV.posMiddle(b)}};
cbCV.dialog.getPreview=function(a,b,n,k,f,h){var r=$("<div></div>");cbCV.s.bg=a;cbCV.s.bc=b;cbCV.s.fc=n;cbCV.style.normalizeHex();h||="Close";cbCV.dialog.config.width="500px";cbCV.dialog.config.title=k;cbCV.dialog.config.content=f;cbCV.dialog.config.button=h;r.append(cbCV.style.getCSSText("common"));r.append(cbCV.style.getCSSText("dialog"));r.append(cbCV.dialog.html);r.find(".CBUI-dialog-title").html(cbCV.dialog.config.title);r.find(".CBUI-dialog-content").html(cbCV.dialog.config.content);r.find(".CBUI-dialog-close").html(cbCV.dialog.config.button);
r.find(".CBUI-dialog").css("width",cbCV.dialog.config.width).removeClass("CBUI-hide");return r.html()};cbCV.dialog.build=function(){cbCV.style.add("dialog");cbCV.s.$b.append(cbCV.dialog.html)};cbCV.dialog.wire=function(a){$(window).on("resize.CBUI-dialog",function(b){cbCV.posMiddle($(".CBUI-dialog"))});if(cbCV.dialog.config.showClose)$(".CBUI-dialog-close").on("click",function(b){if("function"===typeof cbCV.dialog.config.onClose)cbCV.dialog.config.onClose(a);cbCV.dialog.hide();cbCV.dialog.destroy()})};
cbCV.dialog.hide=function(){$(".CBUI-dialog").addClass("CBUI-hide");cbCV.overlay.hide()};cbCV.dialog.destroy=function(){$(window).off("resize.CBUI-dialog");$(".CBUI-dialog").remove()};cbCV.dialog.html='<div class="CBUI-dialog CBUI-hide"><div class="CBUI-dialog-container"><div class="CBUI-dialog-innerContainer"><div class="CBUI-dialog-title">[title]</div><div class="CBUI-dialog-content">[content]</div><div class="CBUI-dialog-footer"><a class="CBUI-dialog-close CBUI-ap">[button]</a></div></div></div></div>';
cbCV.ff={_hash:"",_subject:"",_url:"",_social:[],_body:""};cbCV.ff.init=function(a){var b="Forward to a Friend";cbCV.ff._hash=a.hash;cbCV.ff._subject=a.subject;cbCV.ff._body=a.body;cbCV.ff._social=a.social.split(",");cbCV.ff._url=window.location.protocol+"//"+window.location.hostname+"/cv/"+cbCV.ff._hash;""!==a.title&&(b=a.title);cbCV.style.add("forwardFriend");cbCV.dialog.show({title:b,content:cbCV.ff.html,onOpen:cbCV.ff.wire,width:"620px"})};
cbCV.ff.wire=function(a){var b=encodeURIComponent(cbCV.ff._url),n=cbCV.ff._body.replace(/%0A/gi," "),k=encodeURIComponent(n.replace(/\[url\]/gi,""));a.find("#CBUI-forwardfriend-button").on("click",cbCV.ff.mail);a.find("#CBUI-forwardfriend-url").attr("href",cbCV.ff._url).html(cbCV.ff._url);n=encodeURIComponent(n.replace(/\[url\]/gi,cbCV.ff._url));cbCV.ff._social.length&&""!==cbCV.ff._social[0]?($.each(cbCV.ff._social,function(h,r){a.find("#CBUI-forwardfriend-"+r).removeClass("CBUI-hide")}),a.find("#CBUI-forwardfriend-facebook").attr("href",
"https://www.facebook.com/share.php?u="+b+"&t="+n),a.find("#CBUI-forwardfriend-twitter").attr("href","https://twitter.com/intent/tweet?text="+k+"+"+b),a.find("#CBUI-forwardfriend-linkedin").attr("href","https://www.linkedin.com/shareArticle?mini=true&url="+b+"&title="+n),a.find("#CBUI-forwardfriend-stumbleupon").attr("href","https://www.stumbleupon.com/submit?url="+b+"&title="+n),a.find("#CBUI-forwardfriend-digg").attr("href","https://digg.com/submit?url="+b+"&title="+n),a.find("#CBUI-forwardfriend-delicious").attr("href",
"https://del.icio.us/post?url="+b+"&title="+n),a.find("#CBUI-forwardfriend-reddit").attr("href","https://reddit.com/submit?url="+b+"&title="+n),a.find("#CBUI-forwardfriend-tumblr").attr("href","https://www.tumblr.com/share?v=3&u="+b+"&t="+n),a.find("#CBUI-forwardfriend-google").attr("href","https://plus.google.com/share?url="+b)):(a.find("#CBUI-forwardfriend-socialTitle").addClass("CBUI-hide"),a.find("#CBUI-forwardfriend-socialContent").addClass("CBUI-hide"));try{var f=Clipboard.isSupported()}catch(h){f=
!1}f?new Clipboard($("#CBUI-forwardfriend-clipboard").get(0),{text:function(h){return cbCV.ff._url}}):$("#CBUI-forwardfriend-clipboard-container").addClass("CBUI-hide")};cbCV.ff.mail=function(){var a=cbCV.ff._body.replace(/&/g,"%26"),b="mailto:?subject="+cbCV.ff._subject.replace(/&/g,"%26");a=-1===a.indexOf("[url]")?a+("%0A%0A"+cbCV.ff._url):a.replace(/\[url\]/gi,cbCV.ff._url);window.location.href=b+("&body="+a)};cbCV.ff.html='<a id="CBUI-forwardfriend-button" class="CBUI-ap">Click here to forward this message</a> from your default email program.<br/><br/>Or copy and paste the URL below to share the message.<br/><div id="CBUI-forwardfriend-clipboard-container"><a id="CBUI-forwardfriend-clipboard" class="CBUI-ap">Click here</a> to copy the URL to your clipboard.</div><br /><a id="CBUI-forwardfriend-url" href=""></a><br/><br/><div id="CBUI-forwardfriend-socialTitle">Share on</div><div id="CBUI-forwardfriend-socialContent"><a id="CBUI-forwardfriend-twitter" title="Share on Twitter" class="ap CBUI-forwardfriend-socialIcon CBUI-hide">Share on Twitter</a><a id="CBUI-forwardfriend-facebook" title="Share on Facebook" class="CBUI-forwardfriend-socialIcon CBUI-hide ap">Share on Facebook</a><a id="CBUI-forwardfriend-linkedin" title="Share on LinkedIn" class="ap CBUI-forwardfriend-socialIcon CBUI-hide">Share on LinkedIn</a>\x3c!--<a id="CBUI-forwardfriend-google" title="Share on Google Plus" class="CBUI-forwardfriend-socialIcon CBUI-hide CBUI-ap">Share on Google Plus</a>--\x3e\x3c!--<a id="CBUI-forwardfriend-myspace" title="Share on MySpace" class="CBUI-ap CBUI-forwardfriend-socialIcon CBUI-hide">Share on MySpace</a>--\x3e\x3c!--<a id="CBUI-forwardfriend-stumbleupon" title="Share on StumbleUpon" class="CBUI-ap CBUI-forwardfriend-socialIcon CBUI-hide">Share on StumbleUpon</a>--\x3e<a id="CBUI-forwardfriend-digg" title="Share on digg" class="CBUI-ap CBUI-forwardfriend-socialIcon CBUI-hide">Share on digg</a>\x3c!--<a id="CBUI-forwardfriend-delicious" title="Share on delicious" class="CBUI-ap CBUI-forwardfriend-socialIcon CBUI-hide">Share on delicious</a>--\x3e<a id="CBUI-forwardfriend-reddit" title="Share on reddit" class="CBUI-ap CBUI-forwardfriend-socialIcon CBUI-hide">Share on reddit</a><a id="CBUI-forwardfriend-tumblr" title="Share on Tumblr" class="CBUI-ap CBUI-forwardfriend-socialIcon CBUI-hide">Share on Tumblr</a></div>';
cbCV.poll={heading:"Thank You",message:"Thank you for your response.",button:"Close",preview:!1};cbCV.poll.parseIcal=function(a){""!=cbCV.s.mi&&-1!=a.indexOf("[ical]")&&(a=a.replace(/\[ical\]/g,cbCV.s.mi));return a};
cbCV.poll.init=function(a){var b={};"string"===typeof a.heading&&""!==a.heading&&(cbCV.poll.heading=decodeURIComponent(a.heading));"string"===typeof a.message&&""!==a.message&&(cbCV.poll.message=cbCV.poll.parseIcal(decodeURIComponent(a.message.replace(/%0A/gi,"<br>"))));"string"===typeof a.button&&""!==a.button&&(cbCV.poll.button=decodeURIComponent(a.button));"bool"===typeof a.preview&&(cbCV.poll.message.preview=a.preview);b.title=cbCV.poll.heading;b.content=cbCV.poll.message;b.button=cbCV.poll.button;
b.width="600px";b.preview=a.preview;cbCV.dialog.show(b)};
cbCV.detectFlash=function(){var a=window,b=navigator,n=[0,0,0],k=null;if("undefined"!==typeof b.plugins&&"object"===typeof b.plugins["Shockwave Flash"])(k=b.plugins["Shockwave Flash"].description)&&"undefined"!==typeof b.mimeTypes&&b.mimeTypes["application/x-shockwave-flash"]&&b.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(k=k.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),n[0]=parseInt(k.replace(/^(.*)\..*$/,"$1"),10),n[1]=parseInt(k.replace(/^.*\.(.*)\s.*$/,"$1"),10),n[2]=/[a-zA-Z]/.test(k)?parseInt(k.replace(/^.*[a-zA-Z]+(.*)$/,
"$1"),10):0);else if("undefined"!==typeof a.ActiveXObject)try{if(k=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))k=k.split(" ")[1].split(","),n=[parseInt(k[0],10),parseInt(k[1],10),parseInt(k[2],10)]}catch(f){}return{pv:n}};
(function(a){"object"===typeof exports&&"undefined"!==typeof module?module.exports=a():"function"===typeof define&&define.amd?define([],a):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).Clipboard=a()})(function(){return function f(b,n,k){function h(t,c){if(!n[t]){if(!b[t]){var g="function"==typeof require&&require;if(!c&&g)return g(t,!0);if(r)return r(t,!0);c=Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c;}c=n[t]=
{exports:{}};b[t][0].call(c.exports,function(w){var d=b[t][1][w];return h(d?d:w)},c,c.exports,f,b,n,k)}return n[t].exports}for(var r="function"==typeof require&&require,z=0;z<k.length;z++)h(k[z]);return h}({1:[function(b,n,k){"undefined"===typeof Element||Element.prototype.matches||(b=Element.prototype,b.matches=b.matchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector||b.webkitMatchesSelector);n.exports=function(f,h){for(;f&&9!==f.nodeType;){if("function"===typeof f.matches&&
f.matches(h))return f;f=f.parentNode}}},{}],2:[function(b,n,k){function f(r,z,t,c){return function(g){g.delegateTarget=h(g.target,z);g.delegateTarget&&c.call(r,g)}}var h=b("./closest");n.exports=function(r,z,t,c,g){var w=f.apply(this,arguments);r.addEventListener(t,w,g);return{destroy:function(){r.removeEventListener(t,w,g)}}}},{"./closest":1}],3:[function(b,n,k){k.node=function(f){return void 0!==f&&f instanceof HTMLElement&&1===f.nodeType};k.nodeList=function(f){var h=Object.prototype.toString.call(f);
return void 0!==f&&("[object NodeList]"===h||"[object HTMLCollection]"===h)&&"length"in f&&(0===f.length||k.node(f[0]))};k.string=function(f){return"string"===typeof f||f instanceof String};k.fn=function(f){return"[object Function]"===Object.prototype.toString.call(f)}},{}],4:[function(b,n,k){function f(t,c,g){t.addEventListener(c,g);return{destroy:function(){t.removeEventListener(c,g)}}}function h(t,c,g){Array.prototype.forEach.call(t,function(w){w.addEventListener(c,g)});return{destroy:function(){Array.prototype.forEach.call(t,
function(w){w.removeEventListener(c,g)})}}}var r=b("./is"),z=b("delegate");n.exports=function(t,c,g){if(!t&&!c&&!g)throw Error("Missing required arguments");if(!r.string(c))throw new TypeError("Second argument must be a String");if(!r.fn(g))throw new TypeError("Third argument must be a Function");if(r.node(t))return f(t,c,g);if(r.nodeList(t))return h(t,c,g);if(r.string(t))return z(document.body,t,c,g);throw new TypeError("First argument must be a String, HTMLElement, HTMLCollection, or NodeList");
}},{"./is":3,delegate:2}],5:[function(b,n,k){n.exports=function(f){if("SELECT"===f.nodeName)f.focus(),f=f.value;else if("INPUT"===f.nodeName||"TEXTAREA"===f.nodeName){var h=f.hasAttribute("readonly");h||f.setAttribute("readonly","");f.select();f.setSelectionRange(0,f.value.length);h||f.removeAttribute("readonly");f=f.value}else{f.hasAttribute("contenteditable")&&f.focus();h=window.getSelection();var r=document.createRange();r.selectNodeContents(f);h.removeAllRanges();h.addRange(r);f=h.toString()}return f}},
{}],6:[function(b,n,k){function f(){}f.prototype={on:function(h,r,z){var t=this.e||(this.e={});(t[h]||(t[h]=[])).push({fn:r,ctx:z});return this},once:function(h,r,z){function t(){c.off(h,t);r.apply(z,arguments)}var c=this;t._=r;return this.on(h,t,z)},emit:function(h){var r=[].slice.call(arguments,1),z=((this.e||(this.e={}))[h]||[]).slice(),t=0,c=z.length;for(t;t<c;t++)z[t].fn.apply(z[t].ctx,r);return this},off:function(h,r){var z=this.e||(this.e={}),t=z[h],c=[];if(t&&r)for(var g=0,w=t.length;g<w;g++)t[g].fn!==
r&&t[g].fn._!==r&&c.push(t[g]);c.length?z[h]=c:delete z[h];return this}};n.exports=f},{}],7:[function(b,n,k){(function(f,h){if("undefined"!==typeof k)h(n,b("select"));else{var r={exports:{}};h(r,f.select);f.clipboardAction=r.exports}})(this,function(f,h){var r=h&&h.__esModule?h:{default:h},z="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"===typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c},t=function(){function c(g,
w){for(var d=0;d<w.length;d++){var p=w[d];p.enumerable=p.enumerable||!1;p.configurable=!0;"value"in p&&(p.writable=!0);Object.defineProperty(g,p.key,p)}}return function(g,w,d){w&&c(g.prototype,w);d&&c(g,d);return g}}();h=function(){function c(g){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");this.resolveOptions(g);this.initSelection()}t(c,[{key:"resolveOptions",value:function(){var g=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};this.action=g.action;this.container=
g.container;this.emitter=g.emitter;this.target=g.target;this.text=g.text;this.trigger=g.trigger;this.selectedText=""}},{key:"initSelection",value:function(){this.text?this.selectFake():this.target&&this.selectTarget()}},{key:"selectFake",value:function(){var g=this,w="rtl"==document.documentElement.getAttribute("dir");this.removeFake();this.fakeHandlerCallback=function(){return g.removeFake()};this.fakeHandler=this.container.addEventListener("click",this.fakeHandlerCallback)||!0;this.fakeElem=document.createElement("textarea");
this.fakeElem.style.fontSize="12pt";this.fakeElem.style.border="0";this.fakeElem.style.padding="0";this.fakeElem.style.margin="0";this.fakeElem.style.position="absolute";this.fakeElem.style[w?"right":"left"]="-9999px";this.fakeElem.style.top=(window.pageYOffset||document.documentElement.scrollTop)+"px";this.fakeElem.setAttribute("readonly","");this.fakeElem.value=this.text;this.container.appendChild(this.fakeElem);this.selectedText=(0,r.default)(this.fakeElem);this.copyText()}},{key:"removeFake",
value:function(){this.fakeHandler&&(this.container.removeEventListener("click",this.fakeHandlerCallback),this.fakeHandlerCallback=this.fakeHandler=null);this.fakeElem&&(this.container.removeChild(this.fakeElem),this.fakeElem=null)}},{key:"selectTarget",value:function(){this.selectedText=(0,r.default)(this.target);this.copyText()}},{key:"copyText",value:function(){var g=void 0;try{g=document.execCommand(this.action)}catch(w){g=!1}this.handleResult(g)}},{key:"handleResult",value:function(g){this.emitter.emit(g?
"success":"error",{action:this.action,text:this.selectedText,trigger:this.trigger,clearSelection:this.clearSelection.bind(this)})}},{key:"clearSelection",value:function(){this.trigger&&this.trigger.focus();document.getSelection().removeAllRanges();document.getSelection().addRange(document.createRange())}},{key:"destroy",value:function(){this.removeFake()}},{key:"action",set:function(){this._action=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"copy";if("copy"!==this._action&&"cut"!==this._action)throw Error('Invalid "action" value, use either "copy" or "cut"');
},get:function(){return this._action}},{key:"target",set:function(g){if(void 0!==g)if(g&&"object"===("undefined"===typeof g?"undefined":z(g))&&1===g.nodeType){if("copy"===this.action&&g.hasAttribute("disabled"))throw Error('Invalid "target" attribute. Please use "readonly" instead of "disabled" attribute');if("cut"===this.action&&(g.hasAttribute("readonly")||g.hasAttribute("disabled")))throw Error('Invalid "target" attribute. You can\'t cut text from elements with "readonly" or "disabled" attributes');
this._target=g}else throw Error('Invalid "target" value, use a valid Element');},get:function(){return this._target}}]);return c}();f.exports=h})},{select:5}],8:[function(b,n,k){(function(f,h){if("undefined"!==typeof k)h(n,b("./clipboard-action"),b("tiny-emitter"),b("good-listener"));else{var r={exports:{}};h(r,f.clipboardAction,f.tinyEmitter,f.goodListener);f.clipboard=r.exports}})(this,function(f,h,r,z){function t(e){return e&&e.__esModule?e:{default:e}}function c(e,q){if("function"!==typeof q&&
null!==q)throw new TypeError("Super expression must either be null or a function, not "+typeof q);e.prototype=Object.create(q&&q.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}});q&&(Object.setPrototypeOf?Object.setPrototypeOf(e,q):e.__proto__=q)}function g(e,q){e="data-clipboard-"+e;if(q.hasAttribute(e))return q.getAttribute(e)}var w=t(h);h=t(r);var d=t(z),p="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&
"function"===typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},l=function(){function e(q,y){for(var D=0;D<y.length;D++){var m=y[D];m.enumerable=m.enumerable||!1;m.configurable=!0;"value"in m&&(m.writable=!0);Object.defineProperty(q,m.key,m)}}return function(q,y,D){y&&e(q.prototype,y);D&&e(q,D);return q}}();z=function(e){function q(y,D){if(!(this instanceof q))throw new TypeError("Cannot call a class as a function");var m=(q.__proto__||Object.getPrototypeOf(q)).call(this);
if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");m=!m||"object"!==typeof m&&"function"!==typeof m?this:m;m.resolveOptions(D);m.listenClick(y);return m}c(q,e);l(q,[{key:"resolveOptions",value:function(){var y=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};this.action="function"===typeof y.action?y.action:this.defaultAction;this.target="function"===typeof y.target?y.target:this.defaultTarget;this.text="function"===typeof y.text?y.text:this.defaultText;
this.container="object"===p(y.container)?y.container:document.body}},{key:"listenClick",value:function(y){var D=this;this.listener=(0,d.default)(y,"click",function(m){return D.onClick(m)})}},{key:"onClick",value:function(y){y=y.delegateTarget||y.currentTarget;this.clipboardAction&&(this.clipboardAction=null);this.clipboardAction=new w.default({action:this.action(y),target:this.target(y),text:this.text(y),container:this.container,trigger:y,emitter:this})}},{key:"defaultAction",value:function(y){return g("action",
y)}},{key:"defaultTarget",value:function(y){if(y=g("target",y))return document.querySelector(y)}},{key:"defaultText",value:function(y){return g("text",y)}},{key:"destroy",value:function(){this.listener.destroy();this.clipboardAction&&(this.clipboardAction.destroy(),this.clipboardAction=null)}}],[{key:"isSupported",value:function(){var y=0<arguments.length&&void 0!==arguments[0]?arguments[0]:["copy","cut"],D=!!document.queryCommandSupported;("string"===typeof y?[y]:y).forEach(function(m){D=D&&!!document.queryCommandSupported(m)});
return D}}]);return q}(h.default);f.exports=z})},{"./clipboard-action":7,"good-listener":4,"tiny-emitter":6}]},{},[8])(8)});
cbCopyToClipboard=function(a){var b=this;this.config={};this.clipPluginOptions={};this.config.win=a.window||window;this.config.selector=a.selector;this.config.getText=a.getText;this.config.getTarget=a.getTarget;this.config.tooltipText=a.tooltipText||"Copied";this.config.tooltipDuration=a.tooltipDuration||1500;this.config.tooltipSelector=a.tooltipSelector||!1;"function"===typeof this.config.getText?this.clipPluginOptions.text=this.config.getText:"function"===typeof this.config.getTarget&&(this.clipPluginOptions.target=
a.getTarget);this.config.selector?isNaN(this.config.tooltipDuration)||0>this.config.tooltipDuration?window.console.log("cbCopyToClipboard: tooltipDuration must be a positive number."):this.clipPluginOptions.text||this.clipPluginOptions.target?(this.clipboard=new this.config.win.Clipboard(this.config.selector,this.clipPluginOptions),this.clipboard.on("success",function(n){var k=b.config.win.$(n.trigger);b.config.tooltipSelector?($(b.config.tooltipSelector).html(b.config.tooltipText),cbG.tooltipResize(k)):
(k.tooltip("option","content",b.config.tooltipText),k.tooltip("open"),setTimeout(function(){k.tooltip("close")},b.config.tooltipDuration));n.clearSelection()}),this.config.tooltipSelector||this.config.win.$(this.config.selector).tooltip({items:this.config.selector,show:!1,hide:!1,close:function(n,k){b.config.win.$(n.target).tooltip("option","content","")},position:{my:"center top",at:"center bottom+10"}})):window.console.log("cbCopyToClipboard: You must provide either a getText or getTarget method."):
window.console.log("cbCopyToClipboard: Selector required.")};cbCopyToClipboard.prototype.destroy=function(){this.config.win.$(this.config.selector).tooltip("destroy");this.clipboard.destroy()};
cbVideo={_support:0,_links:!1,_$content:"",init:function(a){try{this._$content=a.$c}catch(b){return}this._links=a.l?!0:!1;this._render()},_render:function(){if(!this._links){var a="link",b="";if(this._$content.find("a.s_video-link").length)b=this._$content.find("img.s_video");else{b=this._$content.find("img.s_video");if(!b.length)return;a="image"}this._setSupportCode();b.each(function(n,k){var f=$(k);k=f.attr("video-url");var h=f.attr("video-flashvars"),r="true"==f.attr("video-autoplay")?' autoplay="autoplay"':
"",z=f.attr("width"),t=f.attr("height"),c=f.attr("src");"undefined"===typeof k&&(k=f.attr("video-src"));0!==n&&(r="",h=h.replace(/'autoPlay':\s*true/gi,"'autoPlay': false"));n="s_video-"+n;f="link"===a?f.closest("a.s_video-link"):f;1===cbVideo._support?cbVideo._addHTML5Video({$target:f,id:n,width:z,height:t,videoSrc:k,imageSrc:c,isAutoplay:!!r}):(k='<object id="'+n+'" width="'+z+'" height="'+t+'" type="application/x-shockwave-flash" data="http://c.contentsvr.com/video/flowplayer.swf"><param name="movie" value="http://c.contentsvr.com/video/flowplayer.swf" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="flashvars" value="'+
h+'" /><img src="'+c+'" width="'+z+'" height="'+t+'" alt="" title="" border="0" ></object>',h=f.parent(),f.replaceWith(k),n=h.find("#"+n),"object"===typeof cbCV&&cbCV.overlay.isShowing()&&n.addClass("CBUI-visuallyHidden"))})}},_addHTML5Video:function(a){var b=a.$target.parent();a.$target.replaceWith('<video id="'+a.id+'" width="'+a.width+'" height="'+a.height+'" controls="controls"><source type="video/mp4" /><img src="'+a.imageSrc+'" alt="" title="" width="'+a.width+'" border="0" height="'+a.height+
'" /></video><br />');b=b.find("#"+a.id).get(0);b.setAttribute("src",a.videoSrc);b.load();a.isAutoplay&&b.play();return $(b)},_setSupportCode:function(){var a=document.createElement("video");a.canPlayType?"probably"==a.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')?this._support=1:"probably"==a.canPlayType('video/ogg; codecs="theora"')?this._support=2:this._support=-1:this._support=0}};
(function(){function a(d){if(!d||"object"!=typeof d)return d;var p=new d.constructor,l;for(l in d)d.hasOwnProperty(l)&&(p[l]=a(d[l]));return p}function b(d,p){if(d){var l,e=0,q=d.length;if(void 0===q)for(l in d){if(!1===p.call(d[l],l,d[l]))break}else for(l=d[0];e<q&&!1!==p.call(l,e,l);l=d[++e]);return d}}function n(d,p,l){if("object"!=typeof p)return d;d&&p&&b(p,function(e,q){l&&"function"==typeof q||(d[e]=q)});return d}function k(d){var p=d.indexOf(".");if(-1!=p){var l=d.slice(0,p)||"*",e=d.slice(p+
1,d.length),q=[];b(document.getElementsByTagName(l),function(){this.className&&-1!=this.className.indexOf(e)&&q.push(this)});return q}}function f(d){d=d||window.event;d.preventDefault?(d.stopPropagation(),d.preventDefault()):(d.returnValue=!1,d.cancelBubble=!0);return!1}function h(d,p,l){d[p]=d[p]||[];d[p].push(l)}function r(){return"_"+(""+Math.random()).slice(2,10)}function z(d,p,l){var e=this,q=null,y=!1,D,m,v=[],B={},E={},F,H,I,L,N,O;n(e,{id:function(){return F},isLoaded:function(){return null!==
q&&void 0!==q.fp_play&&!y},getParent:function(){return d},hide:function(u){u&&(d.style.height="0px");e.isLoaded()&&(q.style.height="0px");return e},show:function(){d.style.height=O+"px";e.isLoaded()&&(q.style.height=N+"px");return e},isHidden:function(){return e.isLoaded()&&0===parseInt(q.style.height,10)},load:function(u){if(!e.isLoaded()&&!1!==e._fireEvent("onBeforeLoad")){var A=0;b(w,function(){this.unload(function(x){++A==w.length&&((D=d.innerHTML)&&!flashembed.isSupported(p.version)&&(d.innerHTML=
""),u&&(u.cached=!0,h(E,"onLoad",u)),flashembed(d,p,{config:l}))})})}return e},unload:function(u){if(this.isFullscreen()&&/WebKit/i.test(navigator.userAgent))return u&&u(!1),e;if(""!==D.replace(/\s/g,"")){if(!1===e._fireEvent("onBeforeUnload"))return u&&u(!1),e;y=!0;try{q&&(q.fp_close(),e._fireEvent("onUnload"))}catch(A){}setTimeout(function(){q=null;d.innerHTML=D;y=!1;u&&u(!0)},50)}else u&&u(!1);return e},getClip:function(u){void 0===u&&(u=L);return v[u]},getCommonClip:function(){return m},getPlaylist:function(){return v},
getPlugin:function(u){var A=B[u];if(!A&&e.isLoaded()){var x=e._api().fp_getPlugin(u);x&&(A=new g(u,x,e),B[u]=A)}return A},getScreen:function(){return e.getPlugin("screen")},getControls:function(){return e.getPlugin("controls")._fireEvent("onUpdate")},getLogo:function(){try{return e.getPlugin("logo")._fireEvent("onUpdate")}catch(u){}},getPlay:function(){return e.getPlugin("play")._fireEvent("onUpdate")},getConfig:function(u){return u?a(l):l},getFlashParams:function(){return p},loadPlugin:function(u,
A,x,C){"function"==typeof x&&(C=x,x={});var G=C?r():"_";e._api().fp_loadPlugin(u,A,x,G);A={};A[G]=C;C=new g(u,null,e,A);return B[u]=C},getState:function(){return e.isLoaded()?q.fp_getState():-1},play:function(u,A){var x=function(){void 0!==u?e._api().fp_play(u,A):e._api().fp_play()};e.isLoaded()?x():y?setTimeout(function(){e.play(u,A)},50):e.load(function(){x()});return e},getVersion:function(){if(e.isLoaded()){var u=q.fp_getVersion();u.push("flowplayer.js 3.2.4");return u}return"flowplayer.js 3.2.4"},
_api:function(){if(!e.isLoaded())throw"Flowplayer "+e.id()+" not loaded when calling an API method";return q},setClip:function(u){e.setPlaylist([u]);return e},getIndex:function(){return I},_swfHeight:function(){return q.clientHeight}});b("Click* Load* Unload* Keypress* Volume* Mute* Unmute* PlaylistReplace ClipAdd Fullscreen* FullscreenExit Error MouseOver MouseOut".split(" "),function(){var u="on"+this;if(-1!=u.indexOf("*")){u=u.slice(0,u.length-1);var A="onBefore"+u.slice(2);e[A]=function(x){h(E,
A,x);return e}}e[u]=function(x){h(E,u,x);return e}});b("pause resume mute unmute stop toggle seek getStatus getVolume setVolume getTime isPaused isPlaying startBuffering stopBuffering isFullscreen toggleFullscreen reset close setPlaylist addClip playFeed setKeyboardShortcutsEnabled isKeyboardShortcutsEnabled".split(" "),function(){var u=this;e[u]=function(A,x){if(!e.isLoaded())return e;A=void 0!==A&&void 0!==x?q["fp_"+u](A,x):void 0===A?q["fp_"+u]():q["fp_"+u](A);return"undefined"===A||void 0===A?
e:A}});e._fireEvent=function(u){"string"==typeof u&&(u=[u]);var A=u[0],x=u[1],C=u[2],G=u[3],J=0;l.debug&&console.log("$f.fireEvent",[].slice.call(u));e.isLoaded()||"onLoad"!=A||"player"!=x||(q=q||document.getElementById(H),N=e._swfHeight(),b(v,function(){this._fireEvent("onLoad")}),b(B,function(Q,M){M._fireEvent("onUpdate")}),m._fireEvent("onLoad"));if("onLoad"!=A||"player"==x)if("onError"==A&&("string"==typeof x||"number"==typeof x&&"number"==typeof C)&&(x=C,C=G),"onContextMenu"==A)b(l.contextMenu[x],
function(Q,M){M.call(e)});else if("onPluginEvent"==A||"onBeforePluginEvent"==A){if(G=B[x.name||x])return G._fireEvent("onUpdate",x),G._fireEvent(C,u.slice(3))}else{if("onPlaylistReplace"==A){v=[];var R=0;b(x,function(){v.push(new c(this,R++,e))})}if("onClipAdd"==A){if(x.isInStream)return;x=new c(x,C,e);v.splice(C,0,x);for(J=C+1;J<v.length;J++)v[J].index++}var K=!0;"number"==typeof x&&x<v.length&&(L=x,(u=v[x])&&(K=u._fireEvent(A,C,G)),u&&!1===K||(K=m._fireEvent(A,C,G,u)));b(E[A],function(){K=this.call(e,
x,C);this.cached&&E[A].splice(J,1);if(!1===K)return!1;J++});return K}};if("string"==typeof d){var P=document.getElementById(d);if(!P)throw"Flowplayer cannot access element: "+d;d=P}(function(){function u(x){var C=e.hasiPadSupport&&e.hasiPadSupport();if(/iPad|iPhone|iPod/i.test(navigator.userAgent)&&!/.flv$/i.test(v[0].url)&&!C)return!0;e.isLoaded()||!1===e._fireEvent("onBeforeClick")||e.load();return f(x)}$f(d)?($f(d).getParent().innerHTML="",I=$f(d).getIndex(),w[I]=e):(w.push(e),I=w.length-1);O=
parseInt(d.style.height,10)||d.clientHeight;F=d.id||"fp"+r();H=p.id||F+"_api";p.id=H;l.playerId=F;"string"==typeof l&&(l={clip:{url:l}});"string"==typeof l.clip&&(l.clip={url:l.clip});l.clip=l.clip||{};d.getAttribute("href",2)&&!l.clip.url&&(l.clip.url=d.getAttribute("href",2));m=new c(l.clip,-1,e);l.playlist=l.playlist||[l.clip];var A=0;b(l.playlist,function(){var x=this;"object"==typeof x&&x.length&&(x={url:""+x});b(l.clip,function(C,G){void 0!==G&&void 0===x[C]&&"function"!=typeof G&&(x[C]=G)});
l.playlist[A]=x;x=new c(x,A,e);v.push(x);A++});b(l,function(x,C){if("function"==typeof C){if(m[x])m[x](C);else h(E,x,C);delete l[x]}});b(l.plugins,function(x,C){C&&(B[x]=new g(x,C,e))});l.plugins&&void 0!==l.plugins.controls||(B.controls=new g("controls",null,e));B.canvas=new g("canvas",null,e);D=d.innerHTML;setTimeout(function(){""!==D.replace(/\s/g,"")?d.addEventListener?d.addEventListener("click",u,!1):d.attachEvent&&d.attachEvent("onclick",u):(d.addEventListener&&d.addEventListener("click",f,
!1),e.load())},0)})()}function t(d){this.length=d.length;this.each=function(p){b(d,p)};this.size=function(){return d.length}}var c=function(d,p,l){var e=this,q={},y={};e.index=p;"string"==typeof d&&(d={url:d});n(this,d,!0);b("Begin* Start Pause* Resume* Seek* Stop* Finish* LastSecond Update BufferFull BufferEmpty BufferStop".split(" "),function(){var m="on"+this;if(-1!=m.indexOf("*")){m=m.slice(0,m.length-1);var v="onBefore"+m.slice(2);e[v]=function(B){h(y,v,B);return e}}e[m]=function(B){h(y,m,B);
return e};-1==p&&(e[v]&&(l[v]=e[v]),e[m]&&(l[m]=e[m]))});n(this,{onCuepoint:function(m,v){if(1==arguments.length)return q.embedded=[null,m],e;"number"==typeof m&&(m=[m]);var B=r();q[B]=[m,v];l.isLoaded()&&l._api().fp_addCuepoints(m,p,B);return e},update:function(m){n(e,m);l.isLoaded()&&l._api().fp_updateClip(m,p);var v=l.getConfig();n(-1==p?v.clip:v.playlist[p],m,!0)},_fireEvent:function(m,v,B,E){if("onLoad"==m)return b(q,function(I,L){L[0]&&l._api().fp_addCuepoints(L[0],p,I)}),!1;E=E||e;if("onCuepoint"==
m){var F=q[v];if(F)return F[1].call(l,E,B)}v&&-1!="onBeforeBegin,onMetaData,onStart,onUpdate,onResume".indexOf(m)&&(n(E,v),v.metaData&&(E.duration?E.fullDuration=v.metaData.duration:E.duration=v.metaData.duration));var H=!0;b(y[m],function(){H=this.call(l,E,v,B)});return H}});if(d.onCuepoint){var D=d.onCuepoint;e.onCuepoint.apply(e,"function"==typeof D?[D]:D);delete d.onCuepoint}b(d,function(m,v){"function"==typeof v&&(h(y,m,v),delete d[m])});-1==p&&(l.onCuepoint=this.onCuepoint)},g=function(d,p,
l,e){var q=this,y={},D=!1;e&&n(y,e);b(p,function(m,v){"function"==typeof v&&(y[m]=v,delete p[m])});n(this,{animate:function(m,v,B){if(!m)return q;"function"==typeof v&&(B=v,v=500);if("string"==typeof m){var E=m;m={};m[E]=v;v=500}if(B){var F=r();y[F]=B}void 0===v&&(v=500);p=l._api().fp_animate(d,m,v,F);return q},css:function(m,v){if(void 0!==v){var B={};B[m]=v;m=B}p=l._api().fp_css(d,m);n(q,p);return q},show:function(){this.display="block";l._api().fp_showPlugin(d);return q},hide:function(){this.display=
"none";l._api().fp_hidePlugin(d);return q},toggle:function(){this.display=l._api().fp_togglePlugin(d);return q},fadeTo:function(m,v,B){"function"==typeof v&&(B=v,v=500);if(B){var E=r();y[E]=B}this.display=l._api().fp_fadeTo(d,m,v,E);this.opacity=m;return q},fadeIn:function(m,v){return q.fadeTo(1,m,v)},fadeOut:function(m,v){return q.fadeTo(0,m,v)},getName:function(){return d},getPlayer:function(){return l},_fireEvent:function(m,v,B){if("onUpdate"==m){B=l._api().fp_getPlugin(d);if(!B)return;n(q,B);
delete q.methods;D||(b(B.methods,function(){var E=""+this;q[E]=function(){var F=[].slice.call(arguments);F=l._api().fp_invoke(d,E,F);return"undefined"===F||void 0===F?q:F}}),D=!0)}return(B=y[m])?(v=B.apply(q,v),"_"==m.slice(0,1)&&delete y[m],v):q}})},w=[];window.flowplayer=window.$f=function(){var d=null,p=arguments[0];if(!arguments.length)return b(w,function(){if(this.isLoaded())return d=this,!1}),d||w[0];if(1==arguments.length){if("number"==typeof p)return w[p];if("*"==p)return new t(w);b(w,function(){if(this.id()==
p.id||this.id()==p||this.getParent()==p)return d=this,!1});return d}if(1<arguments.length){var l=arguments[1],e=3==arguments.length?arguments[2]:{};"string"==typeof l&&(l={src:l});l=n({bgcolor:"#000000",version:[9,0],expressInstall:"http://static.flowplayer.org/swf/expressinstall.swf",cachebusting:!0},l);if("string"==typeof p){if(-1!=p.indexOf(".")){var q=[];b(k(p),function(){q.push(new z(this,a(l),a(e)))});return new t(q)}var y=document.getElementById(p);return new z(null!==y?y:p,l,e)}if(p)return new z(p,
l,e)}return null};n(window.$f,{fireEvent:function(){var d=[].slice.call(arguments),p=$f(d[0]);return p?p._fireEvent(d.slice(1)):null},addPlugin:function(d,p){z.prototype[d]=p;return $f},each:b,extend:n});"function"==typeof jQuery&&(jQuery.fn.flowplayer=function(d,p){if(!arguments.length||"number"==typeof arguments[0]){var l=[];this.each(function(){var e=$f(this);e&&l.push(e)});return arguments.length?l[arguments[0]]:new t(l)}return this.each(function(){$f(this,a(d),p?a(p):{})})})})();
(function(){function a(c,g){if(g)for(var w in g)g.hasOwnProperty(w)&&(c[w]=g[w]);return c}function b(c,g){var w=[],d;for(d in c)c.hasOwnProperty(d)&&(w[d]=g(c[d]));return w}function n(c,g,w){if(z.isSupported(g.version))c.innerHTML=z.getHTML(g,w);else if(g.expressInstall&&z.isSupported([6,65]))c.innerHTML=z.getHTML(a(g,{src:g.expressInstall}),{MMredirectURL:location.href,MMplayerType:"PlugIn",MMdoctitle:document.title});else if(c.innerHTML.replace(/\s/g,"")||(c.innerHTML="<h2>Flash version "+g.version+
" or greater is required</h2><h3>"+(0<t[0]?"Your version is "+t:"You have no flash plugin installed")+"</h3>"+("A"==c.tagName?"<p>Click here to download latest version</p>":"<p>Download latest version from <a href='http://www.adobe.com/go/getflashplayer'>here</a></p>"),"A"==c.tagName&&(c.onclick=function(){location.href="http://www.adobe.com/go/getflashplayer"})),g.onFail){var d=g.onFail.call(this);"string"==typeof d&&(c.innerHTML=d)}k&&(window[g.id]=document.getElementById(g.id));a(this,{getRoot:function(){return c},
getOptions:function(){return g},getConf:function(){return w},getApi:function(){return c.firstChild}})}var k=document.all,f="function"==typeof jQuery,h=/(\d+)[^\d]+(\d+)[^\d]*(\d*)/,r={width:"100%",height:"100%",id:"_"+(""+Math.random()).slice(9),allowfullscreen:!0,allowscriptaccess:"always",quality:"high",version:[3,0],onFail:null,expressInstall:null,w3c:!1,cachebusting:!1};window.attachEvent&&window.attachEvent("onbeforeunload",function(){__flash_unloadHandler=function(){};__flash_savedUnloadHandler=
function(){}});window.flashembed=function(c,g,w){"string"==typeof c&&(c=document.getElementById(c.replace("#","")));if(c)return"string"==typeof g&&(g={src:g}),new n(c,a(a({},r),g),w)};var z=a(window.flashembed,{conf:r,getVersion:function(){var c;try{var g=navigator.plugins["Shockwave Flash"].description.slice(16)}catch(w){try{g=(c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),c.GetVariable("$version"))}catch(d){try{g=(c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),c.GetVariable("$version"))}catch(p){}}}return(g=
h.exec(g))?[g[1],g[3]]:[0,0]},asString:function(c){if(null===c||void 0===c)return null;var g=typeof c;"object"==g&&c.push&&(g="array");switch(g){case "string":return c=c.replace(RegExp('(["\\\\])',"g"),"\\$1"),c=c.replace(/^\s?(\d+\.?\d+)%/,"$1pct"),'"'+c+'"';case "array":return"["+b(c,function(d){return z.asString(d)}).join(",")+"]";case "function":return'"function()"';case "object":g=[];for(var w in c)c.hasOwnProperty(w)&&g.push('"'+w+'":'+z.asString(c[w]));return"{"+g.join(",")+"}"}return String(c).replace(/\s/g,
" ").replace(/'/g,'"')},getHTML:function(c,g){c=a({},c);var w='<object width="'+c.width+'" height="'+c.height+'" id="'+c.id+'" name="'+c.id+'"';c.cachebusting&&(c.src+=(-1!=c.src.indexOf("?")?"&":"?")+Math.random());w=c.w3c||!k?w+(' data="'+c.src+'" type="application/x-shockwave-flash"'):w+' classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"';w+=">";if(c.w3c||k)w+='<param name="movie" value="'+c.src+'" />';c.width=c.height=c.id=c.w3c=c.src=null;c.onFail=c.version=c.expressInstall=null;for(var d in c)c[d]&&
(w+='<param name="'+d+'" value="'+c[d]+'" />');c="";if(g){for(var p in g)g[p]&&(d=g[p],c+=p+"="+(/function|object/.test(typeof d)?z.asString(d):d)+"&");c=c.slice(0,-1);w+='<param name="flashvars" value=\''+c+"' />"}return w+"</object>"},isSupported:function(c){return t[0]>c[0]||t[0]==c[0]&&t[1]>=c[1]}}),t=z.getVersion();f&&(jQuery.tools=jQuery.tools||{version:"3.2.4"},jQuery.tools.flashembed={conf:r},jQuery.fn.flashembed=function(c,g){return this.each(function(){$(this).data("flashembed",flashembed(this,
c,g))})})})();var cbB5;
(()=>{var a={d:(k,f)=>{for(var h in f)a.o(f,h)&&!a.o(k,h)&&Object.defineProperty(k,h,{enumerable:!0,get:f[h]})},o:(k,f)=>Object.prototype.hasOwnProperty.call(k,f),r:k=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(k,Symbol.toStringTag,{value:"Module"});Object.defineProperty(k,"__esModule",{value:!0})}},b={};a.r(b);a.d(b,{View:()=>n});class n{constructor(){}static postRender(k){let f=1<arguments.length&&void 0!==arguments[1]?arguments[1]:$("html");"recipientEmailView"===k?
(f.find("[data-cb-builder-only]").remove(),f.find("[data-cb-web-only]").hide(),f.find("[data-cb-campaign-view-only]").hide()):"recipientWebView"!==k&&"campaignView"!==k||(f.find("[data-cb-web-only]").show(),f.find("[data-cb-email-only]").remove(),"campaignView"===k?(f.find("[data-cb-campaign-view-only]").show(),f.find("[data-cb-recipient-view-only]").remove()):f.find("[data-cb-campaign-view-only]").remove(),f.find(".cb-video-css").remove(),f.find("head").append('\n\t\t\t\t<style type="text/css" class="cb-force-video-css">\n\t\t\t\t\t.cb-video-wrapper { display:block!important; }\n\t\t\t\t\t.cb-video-fallback {  display:none!important; }\n\t\t\t\t</style>\n\t\t\t'),
this.handleViewVideoAutoPlay(f))}static handleViewVideoAutoPlay(){let k=0<arguments.length&&void 0!==arguments[0]?arguments[0]:$("body"),f=k.find("video");try{var h=(new URLSearchParams(window.location.search)).get("autoplay")}catch(r){h=this.getQSParam("autoplay")}if(h)this.videoPlayById(k,h);else if(h=f.filter("[autoplay]"),h.length){let r=!1;h.each((z,t)=>{if(0<t.currentTime)return r=!0,!1});r||this.manualVideoPlay(h.get(0))}f.removeAttr("data-cb-id")}static videoPlayById(){var k=0<arguments.length&&
void 0!==arguments[0]?arguments[0]:$("body");let f=1<arguments.length?arguments[1]:void 0;k=k.find("video");let h=k.filter('[data-cb-id="'+f+'"]').get(0);if(h){var r=!1;k.filter("[autoplay]").each((z,t)=>{t.getAttribute("data-cb-id")===f&&0<t.currentTime?r=!0:t.pause()});r?h.scrollIntoView():(h.scrollIntoView(),this.manualVideoPlay(h))}}static manualVideoPlay(k){let f=k.play();void 0!==f&&"function"==typeof f.then&&f.catch(h=>{k.muted=!0;k.play()})}static getQSParam(k){k=escape(unescape(k));var f=
[],h=null;if(-1<window.location.search.search(k)&&(h=window.location.search.substr(1,window.location.search.length).split("&")),null==h)return null;for(var r=0;r<h.length;r++)escape(unescape(h[r].split("=")[0]))==k&&f.push(h[r].split("=")[1]);return 0==f.length?null:1==f.length?f[0]:f}}cbB5=b})();
//# sourceMappingURL=js_cv_min.js.map
